# Generated by Django 2.2.11 on 2020-03-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20200312_1224'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='callendrecord',
            name='callendrecord_unique_callid',
        ),
        migrations.RemoveConstraint(
            model_name='callstartrecord',
            name='callstartrecord_unique_callid',
        ),
    ]
