# Generated by Django 2.2.11 on 2020-03-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20200323_1313'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='callendrecord',
            index=models.Index(fields=['timestamp'], name='idx_callendrecord_timestamp'),
        ),
    ]
